# Generated by Django 5.0.7 on 2024-08-11 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='completed',
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('IP', 'In Progress'), ('C', 'Completed'), ('OH', 'On Hold'), ('X', 'Canceled')], default='P', max_length=2),
        ),
    ]
